project_id = "bjwmcmmxqsuiclabmxtm"

[functions.ga4-data]
verify_jwt = false

[functions.subbly-data]
verify_jwt = false

[functions.mailchimp-data]
verify_jwt = false

[functions.meta-ads-data]
verify_jwt = false

[functions.google-ads-data]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false

[functions.meta-campaign-insights]
verify_jwt = false

[functions.meta-creative-analysis]
verify_jwt = false

[functions.shopify-data]
verify_jwt = false
